### ISSUE TITLE
corsica -h nit picking

### ISSUE THREAD

**Issue by RAMilewski** [mozilla/corsica-cli#3]
[options] could be confusing:

Usage:  corsica [options] command
 
...and in Commands:
start [options]
restart [options]

Nowhere does it explain that the (only?) option legal in the **start**  and **restart** commands is _--background_.

Maybe list start and restart twice, once each with the --background "option"?

**Comment by RAMilewski** [comment]
... and the restart command is missing.

**Comment by potch** [comment]
I agree- a quirk of the automatic helptext generator. If you say `corscia start -h`, you get the specific options (which as you say is just --background). I can probably do better than the auto helptext here, I'll take a look.
